
  const modal = document.getElementById("modal");
  const modalTitle = document.getElementById("modal-title");
  const modalText = document.getElementById("modal-text");
  const closeBtn = document.querySelector(".close-button");

  const fullContent = {
    "Football": "Football is a family of team sports... [Football is a family of team sports that involve, to varying degrees, kicking a ball to score a goal. Unqualified, the word football generally means the form of football that is the most popular where the word is used. Sports commonly called football include association football (known as soccer in Australia, Canada, South Africa, the United States, and sometimes in Ireland and New Zealand); Australian rules football; Gaelic football; gridiron football (specifically American football, arena football, or Canadian football); International rules football; rugby league football; and rugby union football.[1] These various forms of football share, to varying degrees, common origins and are known as football codes]",
    "Chess": "Chess is a board game for two players... [Chess is a board game for two players. It is an abstract strategy game that involves no hidden information and no elements of chance. It is played on a square board consisting of 64 squares arranged in an 8×8 grid. The players, referred to as White and Black, each control sixteen pieces: one king, one queen, two rooks, two bishops, two knights, and eight pawns, with each type of piece having a different pattern of movement. An enemy piece may be captured (removed from the board) by moving one's own piece onto the square it occupies. The object of the game is to checkmate(threaten with inescapable capture) the enemy king. There are also several ways a game can end in a draw The recorded history of chess goes back to at least the emergence of chaturanga—also thought to be an ancestor to similar games like xiangqi and shogi—in seventh-century India. After its introduction in Persia, it spread to the Arab world and then to Europe. The modern rules of chess emerged in Europe at the end of the 15th century, with standardization and universal acceptance by the end of the 19th century. Today, chess is one of the world's most popular games, with millions of players worldwide.]",
    "Cricket": "Cricket is a bat-and-ball game... [The ICC Men's Cricket World Cup is a quadrennial world cup for cricket in One Day International (ODI) format, organised by the International Cricket Council (ICC). The tournament is one of the world's most viewed sporting events and considered the flagship event of the international cricket calendar by the ICC The first Cricket World Cup was organised in England in June 1975, with the first ODI cricket match having been played only four years earlier. However, a separate Women's Cricket World Cup had been held two years before the first men's tournament, and a tournament involving multiple international teams had been held as early as 1912, when a triangular tournament of Test matches was played between Australia, England and South Africa. The first three World Cups were held in England. From the 1987 tournament onwards, hosting has been shared between countries under an unofficial rotation system, with 14 ICC members having hosted at least one match in the tournament.]",
    "Basketball": "Basketball is a team sport... [Basketball is a team sport in which two teams, most commonly of five players each, opposing one another on a rectangular court, compete with the primary objective of shooting a basketball (approximately 9.4 inches (24 cm) in diameter) through the defender's hoop (a basket 18 inches (46 cm) in diameter mounted 10 feet (3.05 m) high to a backboard at each end of the court), while preventing the opposing team from shooting through their own hoop. A field goal is worth two points, unless made from behind the three-point line, when it is worth three. After a foul, timed play stops and the player fouled or designated to shoot a technical foul is given one, two or three one-point free throws. The team with the most points at the end of the game wins, but if regulation play expires with the score tied, an additional period of play (overtime) is mandated.Players advance the ball by bouncing it while walking or running (dribbling) or by passing it to a teammate, both of which require considerable skill. On offense, players may use a variety of shots – the layup, the jump shot, or a dunk; on defense, they may steal the ball from a dribbler, intercept passes, or block shots; either offense or defense may collect a rebound, that is, a missed shot that bounces from rim or backboard. It is a violation to lift or drag one's pivot foot without dribbling the ball, to carry it, or to hold the ball with both hands then resume dribbling.]",
    "Hockey": "Hockey is a term used to denote a family... [Hockey is a term used to denote a family of various types of both summer and winter team sports which originated on either an outdoor field, sheet of ice, or dry floor such as in a gymnasium. While these sports vary in specific rules, numbers of players, apparel, and playing surface, they share broad characteristics of two opposing teams using sticks to propel a ball or disk into a goal.There are many types of hockey. Some games make the use of skates, either wheeled or bladed, while others do not. In order to help make the distinction between these various games, the word hockey is often preceded by another word, as in field hockey, ice hockey, roller hockey, rink hockey, or floor hockey.Each side may only strike the shuttlecock once before it passes over the net. Play ends once the shuttlecock has struck the floor or ground, or if a fault has been called by the umpire, service judge, or (in their absence) the opposing side.Playable at all levels of society and at all ages, tennis can be played by anyone who can hold a racket, including wheelchair users. The original forms of tennis developed in France during the late Middle Ages.[3] The modern form of tennis originated in Birmingham, England, in the late 19th century as lawn tennis.[4] It had close connections to various field (lawn) games such as croquet and bowls as well as to the older racket sport today called real tennis]",
    "Badminton": "Badminton is a racquet sport... [Badminton is a racquet sport played using racquets to hit a shuttlecock across a net. Although it may be played with larger teams, the most common forms of the game are singles (with one player per side) and doubles (with two players per side). Badminton is often played as a casual outdoor activity in a yard or on a beach; professional games are played on a rectangular indoor court. Points are scored by striking the shuttlecock with the racquet and landing it within the other team's half of the court, within the set boundaries.]",
    "Tennis": "Tennis is a racket sport... [Tennis is a racket sport that is played either individually against a single opponent (singles) or between two teams of two players each (doubles). Each player uses a tennis racket strung with a cord to strike a hollow rubber ball covered with felt over or around a net and into the opponent's court. The object is to manoeuvre the ball in such a way that the opponent is not able to play a valid return. If a player is unable to return the ball successfully, the opponent scores a point]",
    "Boxing": "Boxing is a combat sport and martial art... [Boxing[b] is a combat sport and martial art.[1] Taking place in a boxing ring, it involves two people – usually wearing protective equipment, such as protective gloves, hand wraps, and mouthguards – throwing punches at each other for a predetermined amount of time.Although the term boxing is commonly attributed to western boxing, in which only fists are involved, it has developed in different ways in different geographical areas and cultures of the World. In global terms, boxing today is also a set of combat sports focused on striking, in which two opponents face each other in a fight using at least their fists, and possibly involving other actions, such as kicks, elbow strikes, knee strikes, and headbutts, depending on the rules. Some of these variants are the bare-knuckle boxing, kickboxing, Muay Thai, Lethwei, savate, and sanda.[2][3] Boxing techniques have been incorporated into many martial arts, military systems, and other combat sports.]",
  };

  document.querySelectorAll(".container").forEach(container => {
    const title = container.querySelector("h1").innerText;
    const button = container.querySelector("button");

    button.addEventListener("click", () => {
      modalTitle.innerText = title;
      modalText.innerText = fullContent[title] || "Full content not available.";
      modal.style.display = "block";
    });
  });

  closeBtn.onclick = function() {
    modal.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target === modal) {
      modal.style.display = "none";
    }
  }

